// This file is automatically generated from your SCSS. Any edits will be overwritten.
export const button: string;
export const buttonOutline: string;
export const buttonRounded: string;
export const rippleEffect: string;
export const rippleAnimation: string;
